name: Upload coverage reports to Codecov
on:
  push:
    branches: ["5-stable"]
  pull_request:
    branches: ["5-stable"]
jobs:
  codecov:
    runs-on: ubuntu-latest
    container: perl:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install modules
        run:  cpanm --installdeps .
      - name: Install modules for the coverage
        run: |
          cpanm --quiet --notest Module::Build Module::Build::Tiny Devel::Cover Devel::Cover::Report::Codecovbash
          perl Build.PL 
          ./Build build
      - name: Execute cover command
        run:  cover -test -report codecovbash
      - name: Run Codecov on GitHub Actions
        uses: codecov/codecov-action@v4.0.1
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

